#!/bin/bash
#
# install_tty0tty.sh
# Build, install, persist and load the tty0tty null-modem module with N ports,
# PLUS friendly /dev/<alias> symlinks so picky serial libs recognize the ports.
#
# Defaults:  PAIRS=50  -> /dev/tnt0..tnt99 (100 ports)
#            aliases   -> /dev/ttyUSB100..ttyUSB199  (offset +100 keeps them clear
#                         of real USB-serial adapters such as ttyUSB0 / ttyUSB10-17)
#
# Overrides (env), e.g.:
#   sudo -E PAIRS=16 ./install_tty0tty.sh                       # 16 pairs = 32 ports
#   sudo -E ALIAS_PREFIX=ttyACM ALIAS_OFFSET=0 ./install_...    # /dev/ttyACM0..
#
# Reboot behaviour:
#   * installed .ko, udev rules, modprobe option and boot-time autoload all live
#     on disk -> a plain reboot restores ports AND aliases automatically.
#   * EXCEPTION: a kernel update (new `uname -r`) leaves the .ko under the old
#     /lib/modules/<old>/ ; the new kernel won't find it -> re-run this script.

set -u

# ---------------- config (override via env) ---------------------------------
PAIRS="${PAIRS:-50}"                         # pairs of devices  (ports = 2 * PAIRS)
ALIAS_PREFIX="${ALIAS_PREFIX:-ttyUSB}"       # symlink prefix: ttyUSB / ttyACM / ttyVCOM ...
ALIAS_OFFSET="${ALIAS_OFFSET:-100}"          # symlink index = tnt index + OFFSET

# ---------------- resolve paths relative to THIS script ---------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$SCRIPT_DIR/module"

# ---------------- privilege check -------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
  echo "Needs root (installs a kernel module). Re-run with:" >&2
  echo "    sudo -E $0" >&2
  exit 1
fi

[ -d "$MODULE_DIR" ] || { echo "module/ not found at $MODULE_DIR" >&2; exit 1; }
[ -f "$MODULE_DIR/tty0tty.c" ] || { echo "tty0tty.c missing in $MODULE_DIR" >&2; exit 1; }

cd "$MODULE_DIR" || exit 1

PORTS=$((2 * PAIRS))
LAST=$((PORTS - 1))
ALIAS_FIRST="$ALIAS_OFFSET"
ALIAS_LAST=$((ALIAS_OFFSET + LAST))
echo ">>> target:  $PAIRS pairs = $PORTS ports  (/dev/tnt0..tnt$LAST)"
echo ">>> aliases: /dev/${ALIAS_PREFIX}${ALIAS_FIRST}..${ALIAS_PREFIX}${ALIAS_LAST}  ->  /dev/tnt0..tnt$LAST"
echo

echo "== [1/8] build =="
make clean
make || { echo "build FAILED"; exit 1; }

echo "== [2/8] install .ko + base udev rule (50-tty0tty.rules) =="
make modules_install

echo "== [3/8] depmod =="
depmod -a

echo "== [4/8] modprobe option: pairs=$PAIRS =="
echo "options tty0tty pairs=$PAIRS" > /etc/modprobe.d/tty0tty.conf
echo "    wrote /etc/modprobe.d/tty0tty.conf"

echo "== [5/8] boot-time autoload =="
echo "tty0tty" > /etc/modules-load.d/tty0tty.conf
echo "    wrote /etc/modules-load.d/tty0tty.conf  (loads on every boot)"

echo "== [6/8] generate alias symlinks ($ALIAS_PREFIX*) =="
{
  echo "# Auto-generated by install_tty0tty.sh - regenerated each run; do not edit."
  echo "# /dev/tntN -> /dev/${ALIAS_PREFIX}${ALIAS_FIRST}..${ALIAS_PREFIX}${ALIAS_LAST} ; null-modem pairs preserved"
  echo "# pairs: (tnt0<->tnt1) (${ALIAS_PREFIX}${ALIAS_FIRST}<->${ALIAS_PREFIX}$((ALIAS_FIRST+1))), ..."
  echo "ACTION!=\"add\", GOTO=\"tty0tty_aliases_end\""
  for ((i = 0; i < PORTS; i++)); do
    echo "KERNEL==\"tnt$i\", SYMLINK+=\"${ALIAS_PREFIX}$((ALIAS_OFFSET + i))\""
  done
  echo "LABEL=\"tty0tty_aliases_end\""
} > /etc/udev/rules.d/51-tty0tty-aliases.rules
echo "    wrote /etc/udev/rules.d/51-tty0tty-aliases.rules  ($PORTS symlinks)"

echo "== [7/8] reload udev, unload old, load new (pairs=$PAIRS) =="
udevadm control --reload-rules
if rmmod tty0tty 2>/dev/null; then
  echo "    old module unloaded"
else
  echo "    (old module not loaded, or still IN USE - close programs holding /dev/tnt* and re-run)"
fi
modprobe tty0tty pairs="$PAIRS" || { echo "modprobe FAILED"; exit 1; }
udevadm trigger --subsystem-match=tty --action=add 2>/dev/null || true

echo "== [8/8] verify =="
echo "-- /dev/tnt count (expect $PORTS) --"
ls /dev/tnt* 2>/dev/null | wc -l
echo "-- first alias symlinks --"
ls -l /dev/${ALIAS_PREFIX}${ALIAS_FIRST} /dev/${ALIAS_PREFIX}$((ALIAS_FIRST + 1)) 2>/dev/null
echo "-- aliases pointing to tnt* (expect $PORTS) --"
ls -l /dev/${ALIAS_PREFIX}* 2>/dev/null | grep -c -- '-> /dev/tnt' || true
echo "-- lsmod --"
lsmod | grep -i tty0tty || true
echo "-- dmesg --"
dmesg 2>/dev/null | grep -i tty0tty | tail -3

echo
echo "Done. Pairs: ${ALIAS_PREFIX}${ALIAS_FIRST}<->${ALIAS_PREFIX}$((ALIAS_FIRST+1)), ${ALIAS_PREFIX}$((ALIAS_FIRST+2))<->${ALIAS_PREFIX}$((ALIAS_FIRST+3)), ..."
echo "Reboot-safe for current kernel; re-run after a kernel update."
